# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_NetworkX_path_dock.ui'
#
# Created: Wed Jan 11 11:49:49 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NetworkXPath(object):
    def setupUi(self, NetworkXPath):
        NetworkXPath.setObjectName("NetworkXPath")
        NetworkXPath.resize(447, 473)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NetworkXPath.sizePolicy().hasHeightForWidth())
        NetworkXPath.setSizePolicy(sizePolicy)
        NetworkXPath.setMinimumSize(QtCore.QSize(447, 357))
        NetworkXPath.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.btnOK = QtGui.QPushButton(self.dockWidgetContents)
        self.btnOK.setEnabled(True)
        self.btnOK.setGeometry(QtCore.QRect(350, 410, 81, 27))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtGui.QPushButton(self.dockWidgetContents)
        self.btnCancel.setGeometry(QtCore.QRect(260, 410, 81, 27))
        self.btnCancel.setObjectName("btnCancel")
        self.labelNodes_2 = QtGui.QLabel(self.dockWidgetContents)
        self.labelNodes_2.setEnabled(True)
        self.labelNodes_2.setGeometry(QtCore.QRect(30, 20, 171, 17))
        self.labelNodes_2.setObjectName("labelNodes_2")
        self.comboBoxAlgorithm = QtGui.QComboBox(self.dockWidgetContents)
        self.comboBoxAlgorithm.setEnabled(True)
        self.comboBoxAlgorithm.setGeometry(QtCore.QRect(120, 10, 301, 31))
        self.comboBoxAlgorithm.setObjectName("comboBoxAlgorithm")
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 49, 421, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 170, 411, 131))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.checkBoxUndirected = QtGui.QCheckBox(self.frame)
        self.checkBoxUndirected.setGeometry(QtCore.QRect(110, 130, 161, 22))
        self.checkBoxUndirected.setObjectName("checkBoxUndirected")
        self.labelNodes = QtGui.QLabel(self.frame)
        self.labelNodes.setEnabled(True)
        self.labelNodes.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.labelNodes.setObjectName("labelNodes")
        self.labelEdges = QtGui.QLabel(self.frame)
        self.labelEdges.setGeometry(QtCore.QRect(10, 60, 171, 17))
        self.labelEdges.setObjectName("labelEdges")
        self.comboBoxInputNodes = QtGui.QComboBox(self.frame)
        self.comboBoxInputNodes.setEnabled(True)
        self.comboBoxInputNodes.setGeometry(QtCore.QRect(110, 10, 301, 31))
        self.comboBoxInputNodes.setObjectName("comboBoxInputNodes")
        self.comboBoxInputEdges = QtGui.QComboBox(self.frame)
        self.comboBoxInputEdges.setGeometry(QtCore.QRect(110, 50, 301, 31))
        self.comboBoxInputEdges.setObjectName("comboBoxInputEdges")
        self.labelEdges_2 = QtGui.QLabel(self.frame)
        self.labelEdges_2.setGeometry(QtCore.QRect(10, 100, 171, 17))
        self.labelEdges_2.setObjectName("labelEdges_2")
        self.comboBoxInputWeight = QtGui.QComboBox(self.frame)
        self.comboBoxInputWeight.setGeometry(QtCore.QRect(110, 90, 301, 31))
        self.comboBoxInputWeight.setObjectName("comboBoxInputWeight")
        self.frame_3 = QtGui.QFrame(self.dockWidgetContents)
        self.frame_3.setGeometry(QtCore.QRect(10, 220, 421, 91))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frameOutput = QtGui.QFrame(self.dockWidgetContents)
        self.frameOutput.setGeometry(QtCore.QRect(10, 320, 421, 81))
        self.frameOutput.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOutput.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOutput.setObjectName("frameOutput")
        self.checkBoxOverwrite = QtGui.QCheckBox(self.frameOutput)
        self.checkBoxOverwrite.setGeometry(QtCore.QRect(110, 50, 181, 22))
        self.checkBoxOverwrite.setObjectName("checkBoxOverwrite")
        self.LabelSave = QtGui.QLabel(self.frameOutput)
        self.LabelSave.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.LabelSave.setObjectName("LabelSave")
        self.btnSave_2 = QtGui.QPushButton(self.frameOutput)
        self.btnSave_2.setGeometry(QtCore.QRect(110, 10, 31, 27))
        self.btnSave_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave_2.setIcon(icon)
        self.btnSave_2.setObjectName("btnSave_2")
        self.lineEditSave = QtGui.QLineEdit(self.frameOutput)
        self.lineEditSave.setGeometry(QtCore.QRect(150, 10, 261, 27))
        self.lineEditSave.setObjectName("lineEditSave")
        self.lineEditTargetNode = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEditTargetNode.setGeometry(QtCore.QRect(160, 270, 261, 27))
        self.lineEditTargetNode.setObjectName("lineEditTargetNode")
        self.labelTargetNode = QtGui.QLabel(self.dockWidgetContents)
        self.labelTargetNode.setGeometry(QtCore.QRect(20, 270, 91, 31))
        self.labelTargetNode.setObjectName("labelTargetNode")
        self.labelSourceNode = QtGui.QLabel(self.dockWidgetContents)
        self.labelSourceNode.setGeometry(QtCore.QRect(20, 230, 91, 31))
        self.labelSourceNode.setObjectName("labelSourceNode")
        self.btnTargetNode = QtGui.QPushButton(self.dockWidgetContents)
        self.btnTargetNode.setGeometry(QtCore.QRect(120, 270, 31, 27))
        self.btnTargetNode.setText("")
        self.btnTargetNode.setIcon(icon)
        self.btnTargetNode.setObjectName("btnTargetNode")
        self.btnSourceNode = QtGui.QPushButton(self.dockWidgetContents)
        self.btnSourceNode.setGeometry(QtCore.QRect(120, 230, 31, 27))
        self.btnSourceNode.setText("")
        self.btnSourceNode.setIcon(icon)
        self.btnSourceNode.setObjectName("btnSourceNode")
        self.lineEditSourceNode = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEditSourceNode.setGeometry(QtCore.QRect(160, 230, 261, 27))
        self.lineEditSourceNode.setObjectName("lineEditSourceNode")
        NetworkXPath.setWidget(self.dockWidgetContents)

        self.retranslateUi(NetworkXPath)
        QtCore.QMetaObject.connectSlotsByName(NetworkXPath)

    def retranslateUi(self, NetworkXPath):
        NetworkXPath.setWindowTitle(QtGui.QApplication.translate("NetworkXPath", "NetworkX Plugin - Shortest Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("NetworkXPath", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("NetworkXPath", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNodes_2.setText(QtGui.QApplication.translate("NetworkXPath", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUndirected.setText(QtGui.QApplication.translate("NetworkXPath", "Graph is undirected", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNodes.setText(QtGui.QApplication.translate("NetworkXPath", "Node layer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEdges.setText(QtGui.QApplication.translate("NetworkXPath", "Edge layer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEdges_2.setText(QtGui.QApplication.translate("NetworkXPath", "Weights", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOverwrite.setText(QtGui.QApplication.translate("NetworkXPath", "Overwrite existing files", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelSave.setText(QtGui.QApplication.translate("NetworkXPath", "Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTargetNode.setText(QtGui.QApplication.translate("NetworkXPath", "Target Node", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSourceNode.setText(QtGui.QApplication.translate("NetworkXPath", "Source Node", None, QtGui.QApplication.UnicodeUTF8))

